title: Blueprint
description: A website designer internal documentation
remote_theme: carlosperate/jekyll-theme-rtd
markdown: kramdown
exclude:
  - templates

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/POG-Web-LLC/Blueprint"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
