name: Full-site Docker Image Workflow

on:
  push:
    branches: [ "SCRUM-308" ]
  pull_request:
    branches: [ "SCRUM-308" ]

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: 'latest'
    
    - name: Copy Environment File
      run: cp .env_example .env
    
    - name: Build Docker Images
      run: docker compose build
    
    - name: Save Docker Images as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        run-path: |
          docker images -q
      
  # test-frontend:
  #   runs-on: ubuntu-latest
  #   needs: build-images

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v4

  #   - name: Setup Docker Compose
  #     uses: docker/setup-compose-action@v1
  #     with:
  #       version: 'latest'
    
  #   - name: Run Site Tests
  #     run: |
  #       # Add your test commands here
  #       echo "Running tests..."
  #       # Example: docker exec -it blueprint-site npm run test
    
    